src/components/common/Tabs/index.tsx

commonTabs 컴포넌트를 구현했습니다!
아직 미흡한게 있는것같아서 정리해서 추후에 한번에 수정하도록하겠습니다! (정리는 지라 이슈내용에 하겠습니다. 확인부탁드립니당!)
https://github.com/bucket-back/bucket-back-frontend/assets/104294861/6f182a6c-f5af-4c84-a01c-75b0287c38ea
> By default, the Tabs component renders all tabs content to the DOM, meaning that invisible tabs are still rendered but are hidden by styles.
> 
> If you want to defer rendering of each tab until that tab is selected, you can use the isLazy prop. This is useful if your tabs require heavy performance, or make network calls on mount that should only happen when the component is displayed.
차크라 탭 컴포넌트에서 자체적으로 lazy라는 기능을 제공해주는것같은데
탭에 따라 불러오는 내용이 많아질수록 렌더링이 늦어질수도 있으니 lazy를 적용해보는것도 좋을것같습니다!🧐
그리고 로그인 여부에따라 버튼 보여주기(내가 올린 투표, 참여한 투표) => isDisabled로 처리할까했는데 그렇게되면 너무 단절된느낌이라 클릭하면 로그인여부 확인한다음에 로그인페이지로 …

[OMCT-68] commonTabs 컴포넌트 구현

---

package.json
src/main.tsx
src/mocks/browser.js
src/mocks/handler.ts

msw가 [Service worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)를 이용해서 구현되었는데
이거를 브라우저에 등록하는 로직을 짜봤습니다!
merge가 되면 이 명령어를 `npx msw init public/ --save` 입력하셔야합니다!
하시면 package.json,public 폴더에 mockServiceWorker.js 파일이 생성이 됩니다!
아직 배우고 있는 단계여서 코드가 깔끔하지 않습니다ㅠㅠㅠ

[Omct 75] 브라우저에 Service worker 등록

---

.commitlintrc.json
src/components/common/Divider/index.tsx

CommonDivider 컴포넌트를 구현했습니다.  
사용방법은 `size` prop에 `sm` 혹은 `lg`를 할당하면 됩니다.
`sm`은 1px이고 `lg`는 10px입니다. 
저희 프로젝트에서 수직은 사용하지 않아 추가하지 않았습니다.
추가로 commit 메시지에 파스칼케이스를 사용할 경우 에러가 뜨는 현상이 발생해서 룰을 추가했습니다.

[OMCT-101] CommonDivider 컴포넌트 구현 및 commitlint 룰 추가

---

src/components/common/Slider/index.tsx

CommonSlider 컴포넌트를 구현했습니다.
사용법은 `onChange` prop에 useState의 업데이트 함수를 넣어주면 됩니다.
기본 값으로 `2.5`가 들어가있고 범위는 최소 `0`부터 최대 `5`까지 입니다.
그리고 `0.5`씩 증가/감소됩니다.
리뷰에 점수를 줄때만 사용하기에 이렇게 구현하게 됐습니다. 
```typescript
const [state, setState] = useState(2.5);
return (
<>
<div>{state}</div>
<CommonSlider onChange={setState} />
</>
);
```

[OMCT-103] CommonSlider 컴포넌트 구현

---

src/components/common/Badge/index.tsx

CommonBadge 컴포넌트를 구현했습니다.
`adopt` 타입은 채택, `level` 타입은 레벨, `vote` 타입은 투표에 사용됩니다.
`levelNumber`는 1 ~ 10까지 넣을 수 있고 `count`에는 숫자를 넣으면 됩니다.
```javascript
<CommonBadge type="adopt" />
<CommonBadge type="level" levelNumber={1} />
<CommonBadge type="vote" count={100} />
```

[OMCT-115] CommonBadge 컴포넌트 구현

---

src/components/common/Icon/index.tsx

CommonIcon 컴포넌트를 구현했습니다.
사용법은 아래와 같습니다.
```javascript
<CommonIcon type="crown" color="blue.300" size="1rem" />
```
타입은 아래를 보시고 넣으시면 됩니다.

[OMCT-107] CommonIcon 컴포넌트 구현

---

src/components/common/IconButton/index.tsx

CommonIconButton 컴포넌트를 구현했습니다.
컴포넌트의 props타입은 아래와 같습니다.
```typescript
interface CommonIconButtonProps {
type: 'delete' | 'create' | 'up' | 'update' | 'add' | 'detail' | 'back';
width?: `${number}rem`;
height?: `${number}rem`;
fontSize?: `${number}rem`;
onClick: () => void;
}
```
사용방법은 아래와 같습니다.
```javascript
<CommonIconButton type="create" onClick={() => {}} />
<CommonIconButton type="add" onClick={() => {}} />
<CommonIconButton type="up" onClick={() => {}} />
<CommonIconButton type="detail" onClick={() => {}} />
<CommonIconButton type="delete" onClick={() => {}} />
<CommonIconButton type="update" onClick={() => {}} />
<CommonIconButton type="back" onClick={() => {}} />
```
위의 사용방법의 코드 순서로 타입을 보시면 됩니다.
크기를 디자인에 맞춰서 설정했기때문에 크기를 조정할 수 없는 상태입니다. 추후에 크기 조정이 필요하면 수정하겠습니다.

[OMCT-109] CommonIconButton 컴포넌트 구현

---

src/components/common/Text/index.tsx
src/utils/conformText.ts

CommonText 컴포넌트 구현
-  color,noOfLines(몇줄을 보여줄지),type(title,info에 종류),children(아무 문장을 입력하기 때문에 선언) 를 prorp를 받습니다!
-  유틸함수를 구현해서 title일때는 heading 컴포넌트로 나오게 구현했습니다!
conformText 유틸함수 구현
- type에 따라서 heading을 줘야할지 고민을 하다가 구현했습니다!
- fontFamily는 아직 넣지 않았는데 전역으로 해보고 안되면 바로 추가하겠습니다!
- type에 이름이 어색하면 바로 수정하겠습니다!

[OMCT-113]  CommonText 컴포넌트 구현 및 util 함수 정의

---

src/components/common/Menu/index.tsx

CommonMenu 컴포넌트를 구현했습니다.
타입으로 update, logout, create가 있습니다.
update는 피드, 댓글, 리뷰, 인벤토리에서 쓰이고 
logout은 마이에서 쓰이며
create는 버킷, 아이템에서 쓰입니다.
컴포넌트의 props 타입은 아래와 같습니다.
```typescript
interface CommonMenuProps {
type: 'update' | 'logout' | 'create';
iconSize?: `${number}rem`;
fontSize?: `${number}rem`;
onUpdate?: () => void;
onDelete: () => void;
onLogout?: () => void;
onCreate?: () => void;
}
```
사용방법은 아래와 같습니다.
```javascript
<CommonMenu type="update" onUpdate={() => {}} onDelete={() => {}} />
<CommonMenu type="logout" onLogout={() => {}} onDelete={() => {}} />
<CommonMenu type="create" onCreate={() => {}} onDelete={() => {}} />
```
위 사용방법의 코드 순서로 보시면 됩니다.

[OMCT-104] CommonMenu 컴포넌트 구현

---

src/components/common/Radio/RadioCard.tsx
src/components/common/Radio/index.tsx

CommonRadio 컴포넌트 구현
- 훅을 사용해서 `getRootProps,getRadioProps,getInputProps`를 뺀 이유는 속성을 가져와서 좀 더 쉽게 jsx를 작성하기 위해서 했습니다
- change가 될때마다 re-rendering이 발생해서 디바운스 훅을 따로 제작해서 나중에 다시 pr 올리겠습니다!
- text는 commonText를 사용해서 작성을 해야할것 같습니다!
- props 중 values는 취미 목록(전체)이고 defaultValue는 초기에 선택된 아이템 입니다
```
// 사용방법
import { useState } from 'react';
import CommonRadio from './components/common/Radio/index';
const initalHobby = ['수영', '자전거', '농구'];
const App = () => {
const [selected, setSelected] = useState<string>(initalHobby[1]);
return <CommonRadio values={initalHobby} name="취미" onChange={setSelected} />;
};
export default App;
```

[OMCT-102] CommonRadio 컴포넌트 제작

---

src/components/common/Tag/index.tsx

CommonTag 컴포넌트
- 이벤트 버블링 방지하기 위해서 `e.stopPropagation();`를 추가했습니다!
- `type,onClick`만 선언하면 사용하실수 있습니다! `onDelete`는 필요한 구간만 정의해서 사용하시면 됩니다!
- 확장성있게 짜볼려고 두개이지만 객체로 구현했는데 어떤게 좋을지 궁금합니다!(은근 겹치는 속성들이 많아서 고민입니다ㅠㅠ)
```
// 삼항 연산자로 했을때
import { Tag, TagLabel, TagCloseButton } from '@chakra-ui/react';
import { ReactElement } from 'react';
import CommonIcon from '../Icon/index';
interface CommonTagProps {
isFeed: boolean;
children: ReactElement;
onClick: () => void;
onDelete?: () => void;
}
const CommonTag = ({ isFeed, children, onClick, onDelete }: CommonTagProps) => {
return (
<Tag
onClick={() => onClick()}
size="md"
variant="subtle"
bg={isFeed ? 'blackAlpha.700' : 'blue.100'}
>
<TagLabel>{children}</TagLabel>
{isFeed ? <CommonIcon type="chevronRight" /> : <TagCloseButton onClick={() => onDelete!()} …
```

[OMCT-118] CommonTag 컴포넌트 구현

---

src/components/common/Toast/index.tsx
src/hooks/useCustomToast.tsx

임시방편으로 CommonToast 컴포넌트를 구현했습니다.
toast 훅을 따로 만들었습니다. 🥲
https://github.com/bucket-back/bucket-back-frontend/assets/104294861/a73afb03-813d-440d-a203-d379851f96d2

[OMCT-69] CommonToast 컴포넌트 구현

---

src/components/common/Skeleton/index.tsx

CommonSkeleton 컴포넌트를 구현했습니다.
타입으로, feed, item, bucket, inProgressVote, vote가 있습니다.
feed는 말그대로 피드에 쓰이고
item과 bucket 또한 단어 그대로를 의미합니다.
inProgressVote는 진행중인 투표에서 쓰이고
vote는 종료된 투표에 쓰입니다.
컴포넌트의 props 타입은 아래와 같습니다.
```typescript
interface CommonSkeletonProps {
type: 'feed' | 'item' | 'bucket' | 'inProgressVote' | 'vote';
}
```
사용방법은 아래와 같습니다.
```javascript
<CommonSkeleton type="feed" />
<CommonSkeleton type="item" />
<CommonSkeleton type="bucket" />
<CommonSkeleton type="inProgressVote" />
<CommonSkeleton type="vote" />
```
왼쪽부터 feed, item, bucket, inProgressVote, endVote 순입니다.
<del>`isLoaded` prop은 표시될지 안될지를 나타낼때 사용되지만 저희 프로젝트에서는 미사용 가능성이 있습니다만 일단 추가했습니다.</del>

[OMCT-112] CommonSkeleton 컴포넌트 구현

---

src/components/common/Card/index.tsx

CommonCard 컴포넌트 구현
- CardBody에 `px` 과 CardHeader에 `p` 추가했습니다
- Card에 전체적인 ui 속성을 추가했습니다
- 현재 1곳에만 쓰여서 maxW,minH를 고정시켜서 확장성이 없는데 props로 받으면 확장성이 더 나을것 같은데 다들 생각하시나요??!
- CommonImage 컴포넌트에 이벤트 버블링을 추가하면 좋을것 같습니다!
- CardFooter에 날짜 정보를 넣으면 더 좋을것 같은데 어떻게 생각하시나요??!

[OMCT-117] CommonCard 컴포넌트 구현

---

src/components/common/Button/index.tsx

CommonButton 컴포넌트
- `isDisabled`은 모든 버튼에 해당될것 같아서 다 할당 했습니다!
- `isClick`은 좋아요 버튼에 한정이 될것 같아서 좋아요 버튼에만 할당했습니다
- size 별로 이름을 구분했습니다
- `type[full]`은 이 버튼을 감싸는 전체 layout width가 어떻게 설정하느냐에 따라서 전체적으로 할당되도록 설정하였습니다
- 짜고보니깐 공통된 부분이 많아서 이렇게 하는지 많은지 의문이 들었습니다ㅠㅠ

[OMCT-106] CommonButton 컴포넌트 구현

---

vite.config.ts

경로 별칭 오류를 수정했습니다.
`vite.config.ts`에 경로 별칭에 대한 설정을 했어야 했는데 까먹고 설정을 안해줘서 오류가 발생했습니다.

[OMCT-163] 경로 별칭 오류 수정

---

src/shared/components/Drawer/index.tsx

단위를 rem으로 수정하고 
DrawerOverlay, DrawerContent에 최대넓이와 가운데 정렬을 지정했습니다.
이제 넓이가 변경되면 drawer도 같이 변경됩니다.

[OMCT-156] CommonDrawer 컴포넌트 수정

---

src/shared/components/Image/index.tsx

이전의 반응형은 maxW보다 작은 이미지를 넣었을때 가득차지않는 문제점이 있었어요.🥲
maxW를 삭제하고 width를 기본으로 주되 maxW를 100%로 수정한뒤 작은이미지도 채워질수있도록 수정했어요!
height는 aspectRatio로 대체하여 비율에 맞게 이미지가 줄어들수있도록 했어요!
모달에서도 잘 적용되는 모습이예요!
https://github.com/bucket-back/bucket-back-frontend/assets/104294861/12a0d9a7-1392-4f11-b59a-ea5eb8dec5d4
반응형이 굉장히 말썽이네요ㅠㅅㅠ자주 수정해서 죄송합니다!🥲

[OMCT-179] CommonImage 컴포넌트 작은 이미지 반응형 수정

---

src/shared/components/Footer/index.tsx
src/shared/components/Icon/index.tsx
src/shared/components/IconButton/index.tsx
src/shared/hooks/index.ts
src/shared/hooks/useSamePath.tsx

footer 컴포넌트
- path에 맞게 type 수정 및 icon 이름 수정
- 클릭시 이동가능하도록 기능 추가
- 클릭된 경우 어떤위치인지 표시기능 추가
icon 컴포넌트
- icon 이름 수정(path에 맞게)
- height 꽉차게 해서 가운데 맞게 디자인 수정
iconButton 컴포넌트
- cancel iconButton 추가
iconButton 컴포넌트
footer컴포넌트

[OMCT-186] footer컴포넌트/icon컴포넌트/iconbutton컴포넌트 수정

---

src/core/routes/router.tsx
src/features/vote/components/VoteInProgress/index.tsx
src/features/vote/components/VoteItem/index.tsx
src/features/vote/components/Votes/index.tsx
src/main.css
src/pages/Vote/VoteHome/index.tsx
src/shared/components/Card/index.tsx
src/shared/components/DividerImage/index.tsx
src/shared/components/Tabs/index.tsx

투표 페이지 ui 구현했습니다.
레이아웃을 잡다보니 문제사항이 생겨서 도와주셨으면 합니다! 스크롤이 문제군요...🔥
`<TabPanel p={0} key={index} display="flex" flexDir="column" maxH="60vh">` => 60vh는 임의로 둔것
종료된 투표안에만 세로 스크롤을 추가하기 위해서는 탭컴포넌트의 TabPanel에 height를 지정해줘야 스크롤이 생깁니다.
높이 지정을 안해줬을 경우 넘처 흐릅니다🥲[[관련링크]]( https://github.com/chakra-ui/chakra-ui/issues/361)
또한 높이를 지정해준다해도 반응형을 고려하기에는 어렵습니다ㅠㅠ
너무 작은 화면일때에도 여전히 넘처흐르는 문제점이 있습니다.(se기준)
야매인 방법인것같아서 더 좋은 해결책이 필요해보입니다! 
찬욱님이 수정해주신  Divider Image를 반영하면 overflowx가 먹지를 않습니다..🥲
overflowx를 사용하기위해서는 고정된 width가 필요해보입니다.ㅠㅠ
help....me...................................😇
수정사항이 있다면 언제든지 알려주세요! 감사합니다!

[OMCT-188] 투표 페이지 ui 구현

---

src/core/routes/router.tsx
src/features/feed/components/FeedComment/index.tsx
src/features/feed/components/FeedItem/index.tsx
src/features/feed/components/FeedItem/style.tsx
src/features/feed/components/index.ts
src/pages/Feed/FeedDetail/index.tsx
src/pages/index.ts
src/shared/components/Button/index.tsx
src/shared/components/Header/index.tsx
src/shared/components/Input/index.tsx

FeedDetail 페이지를 구현했습니다.
UI 우선으로 구현하여 기능은 추후에 추가하겠습니다.
style 파일로 아직 분리하지 않았습니다.
CommonInput 컴포넌트의 width prop 타입에 100%를 인자로 넘겨주기위해 string으로 타입을 수정했습니다.
CommonButton 컴포넌트에 xsText 타입의 버튼을 추가했습니다.
Header 컴포넌트의 높이가 줄어드는 현상이 있어서 flexShrink 속성을 추가했습니다.

[OMCT-183] FeedDetail 페이지 구현, CommoInput 컴포넌트 수정, CommonButton 컴포넌트 수정, Header 컴포넌트 수정

---

src/core/routes/router.tsx
src/pages/Member/MemberHome/index.tsx
src/pages/Member/MemberHome/style.tsx
src/pages/index.ts
src/shared/components/Avatar/index.tsx
src/shared/components/Button/index.tsx
src/shared/components/Footer/index.tsx

MemberHome 페이지를 구현했습니다.
UI 우선으로 구현하였고 추후에 기능을 구현하겠습니다.
router의 path 중 user로 작성되어진 부분을 member로 변경하였습니다. 
CommonButton, Avatar 컴포넌트의 타입 중 일부를 옵셔널 타입으로 수정했습니다.
CommonButton 컴포넌트에 profile 버튼 타입을 추가했습니다.

[OMCT-218] MemberHome 페이지 구현

---

src/core/routes/router.tsx
src/pages/Member/MemberPassword/index.tsx
src/pages/Member/MemberPassword/style.tsx
src/pages/index.ts
src/shared/components/Icon/index.tsx

MemberPassword 페이지의 UI를 구현했습니다.

[OMCT-254] MemberPassword 페이지 UI 구현

---

src/features/vote/components/VoteItem/index.tsx
src/features/vote/components/VoteOptionItem/index.tsx
src/features/vote/components/VoteOptionItem/style.ts
src/features/vote/hooks/index.ts
src/features/vote/hooks/useDeleteVote.ts
src/features/vote/hooks/useParticipationVote.ts
src/features/vote/service/queryOption.ts
src/pages/Vote/VoteDetail/index.tsx

투표 상세페이지에 get api를 연동했습니다.
투표 참여하는거까지하려고했는데 테스트하는도중 api가 이상한것같아서 나머지는 추후에 나눠서 pr을 올려야할것같습니다!
https://github.com/bucket-back/bucket-back-frontend/assets/104294861/2303347e-c74a-4790-a351-fce1b2fc73e2

[OMCT-180] 투표 상세페이지 get api 연동

---

src/features/feed/components/FeedItem/index.tsx
src/features/feed/components/FeedItem/style.tsx
src/features/feed/components/FeedItemsDetail/index.tsx
src/features/feed/hooks/index.ts
src/features/feed/hooks/useFeedDetail.ts
src/features/feed/hooks/useFeedLike.ts
src/features/feed/hooks/useFeedUnLike.ts
src/features/feed/hooks/useFeeds.ts
src/features/feed/service/queryOption.ts
src/features/feed/service/types.ts
src/pages/Feed/FeedDetail/index.tsx
src/pages/Feed/FeedHome/index.tsx
src/pages/Member/MemberHome/index.tsx
src/shared/components/Avatar/index.tsx
src/shared/components/Button/index.tsx
src/shared/components/Input/index.tsx
src/shared/components/Profile/index.tsx
src/shared/utils/ellipsisName.ts
src/shared/utils/index.ts

피드 상세 페이지를 수정했습니다.
기존에 useQuery로 만든 훅을 삭제하고 직접 사용하는 방식으로 변경했습니다.
좋아요 기능을 추가했습니다.
로그인 여부에 따른 좋아요, 댓글 사용을 제한했습니다.
추가적으로 자잘한 디자인 및 공통 컴포넌트를 수정했습니다.

[OMCT-285] 피드 상세 페이지 수정 및 좋아요 기능 추가

---

src/features/member/hooks/index.ts
src/features/member/hooks/useLeave.ts
src/features/member/hooks/useLogout.ts
src/features/member/service/index.ts
src/features/member/service/queryOption.ts
src/pages/Member/MemberHome/index.tsx
src/pages/Member/MemberHome/style.tsx
src/shared/constants/index.ts
src/shared/constants/path.ts
src/shared/constants/storage.ts
src/shared/types/member.ts
src/shared/utils/storage.ts

멤버 페이지의 로그아웃, 탈퇴 기능을 구현했습니다.
로그아웃은 useLogout 훅을 사용하여 작동하며,
탈퇴는 useLeave 훅을 사용하여 작동합니다.
2번이상 쓰이는 문자열은 상수로 만들어서 constants 폴더에 추가했습니다.
https://github.com/bucket-back/bucket-back-frontend/assets/40534414/e1e1df12-f3db-4c75-b1b0-8a9dd64fdbbb

[OMCT-287] 멤버 페이지의 로그아웃, 탈퇴 기능 구현

---

src/features/feed/service/queryOption.ts
src/features/feed/service/types.ts
src/pages/Feed/FeedHome/index.tsx
src/pages/Feed/FeedHome/style.tsx
src/pages/Home/index.tsx
src/shared/components/Select/index.tsx

피드 페이지에 select를 추가했습니다.
최신순, 인기순으로 피드 목록을 확인할 수 있습니다.
새로고침시에도 현재 url의 쿼리스트링의 sort값을 확인해서 option을 지정해줍니다.

[OMCT-290] 피드 페이지 select 추가

---

src/features/comment/components/CommentItem/index.tsx
src/pages/Feed/FeedDetail/index.tsx

피드 작성자만 댓글 채택하기 버튼 보이게 수정했습니다.
피드에 채택된 댓글이 있으면 댓글의 채택하기 버튼을 안보이게 수정했습니다.

[OMCT-292] 피드 작성자만 댓글 채택하기 버튼 보이게 수정

---

src/features/feed/components/FeedItem/index.tsx
src/pages/Feed/FeedDetail/index.tsx
src/pages/Member/MemberHome/index.tsx
src/pages/Member/MemberHome/style.tsx
src/shared/components/DividerImage/index.tsx
src/shared/types/feed.ts

멤버 페이지의 인벤토리, 버킷 데이터를 연결했습니다.
피드 상세 페이지의 버킷 총액을 추가했습니다.
DividerImage 컴포넌트의 디자인을 수정했습니다.

[OMCT-307] 멤버 페이지 수정

---

src/core/routes/router.tsx
src/features/hobby/components/HobbyRadio/index.tsx
src/features/hobby/components/HobbyRadio/style.ts
src/features/hobby/components/index.ts
src/pages/Feed/FeedCreate/index.tsx
src/pages/Feed/FeedDetail/index.tsx
src/pages/Feed/FeedUpdate/index.tsx
src/pages/Feed/FeedUpdate/style.ts
src/pages/index.ts
src/shared/components/Radio/index.tsx

피드 수정 페이지 UI를 구현했습니다.
추가로 취미를 선택하는 라디오부분을 컴포넌트로 분리하여 HobbyRadio 컴포넌트로 만들었습니다.
피드를 수정시에는 취미를 변경할 수 없기때문에 isReadOnly라는 prop을 CommonRadio 컴포넌트에 추가했습니다.

[OMCT-330] 피드 수정 페이지 UI 구현 및 HobbyRadio 컴포넌트 추가

---

src/core/routes/router.tsx
src/pages/Bucket/BucketDetail/index.tsx
src/pages/Bucket/BucketDetail/style.ts
src/pages/Bucket/BucketHome/index.tsx
src/pages/Bucket/BucketHome/style.ts
src/pages/index.ts
src/shared/components/Tabs/index.tsx

버킷 목록, 상세 페이지의 UI를 구현했습니다.
취미에 사용되는 Tab의 스타일을 수정했습니다.

[OMCT-341] 버킷 목록, 상세 페이지 UI 구현

---

src/features/comment/components/CommentItem/index.tsx
src/features/comment/hooks/index.ts
src/features/comment/hooks/useAddComment.ts
src/features/comment/hooks/useAdoptComment.ts
src/features/comment/hooks/useDeleteComment.ts
src/features/comment/hooks/useUpdateComment.ts
src/pages/Feed/FeedDetail/index.tsx

댓글 채택 및 수정 api를 연결했습니다.
댓글 관련 기능에서 성공시 나오는 토스트가 없었어서 추가했습니다.
댓글 삭제시 drawer가 나오도록 추가했습니다.

[OMCT-338] 댓글 채택 및 수정 api 연결

---

src/shared/hooks/index.ts
src/shared/hooks/useIntersectionObserver.ts

useIntersectionObserver 훅을 추가했습니다.
인수의 onObserve에는 fetchNextPage를 받으면되고 option은 선택적으로 추가하면 됩니다.
```javascript
const observedRef = useIntersectionObserver({ onObserve: feeds.fetchNextPage, root: (...) });
```

[NO-JIRA] useIntersectionObserver 훅 추가

---

src/features/member/components/MemberEmailForm/index.tsx
src/features/member/components/MemberEmailForm/style.ts
src/features/member/components/MemberNicknameForm/index.tsx
src/features/member/components/MemberNicknameForm/style.ts
src/features/member/components/MemberPassword/index.tsx
src/pages/Member/Signup/index.tsx
src/shared/components/Text/index.tsx
src/shared/styles/GlobalStyle.tsx

1. CommonText에 as props를 추가했습니다.
2. 회원가입페이지에 컴포넌트를 분리하였습니다. => 지금은 종속성이 강해서 추후에 제거할 예정입니다.!

[OMCT-390] 회원가입페이지 컴포넌트 분리, CommonText 수정

---

src/features/inventory/components/InventorySelectItem/index.tsx
src/features/inventory/service/queryOption.ts
src/features/member/components/MemberNicknameForm/index.tsx
src/features/vote/components/VoteSelectItem/index.tsx
src/features/vote/hooks/useCreateVote.ts
src/pages/Inventory/InventoryCreate/index.tsx
src/pages/Inventory/InventoryDetail/index.tsx
src/pages/Member/Login/index.tsx
src/pages/Member/Signup/index.tsx
src/shared/components/Image/index.tsx

1. 투표 생성시 취미에 맞는 아이템을 가져올때 무한스크롤을 적용하였습니다
2. 인벤토리 생성시 리뷰한 아이템을 가져올때 무한스크롤을 적용하였습니다.
3. 투표 생성후 뒤로가기했을때 투표목록으로 이동합니다.
4. 이미지에 border를 추가하였습니다.
5. 로그인, 회원가입페이지에 뒤로가기를 넣었습니다.
6. 닉네임 중복버튼을 클릭했을시 같은 닉네임을 입력했을 경우 api호출이 안되도록 막아두었습니다.

[OMCT-392] qa반영 + 무한스크롤
