bucket-back/bucket-back-frontend

- README.md
> [OMCT-58] 기술스택 수정

- .eslintrc.cjs
- .prettierrc.cjs
- package-lock.json
- package.json
- src/App.tsx
- src/main.tsx
> [OMCT-61] eslint, prettier 세팅 추가

- package-lock.json
- package.json
> [OMCT-64] 기술 스택에 작성된 라이브러리 설치

- src/main.tsx
> [OMCT-70] ChakraProvider 추가

- .commitlintrc.json
- .eslintrc.cjs
- .husky/commit-msg
- .husky/pre-commit
- package-lock.json
- package.json
> [OMCT-120] 라이브러리 추가

- src/components/common/Drawer/index.tsx
CommonDrawer 컴포넌트를 구현했습니다.  
저희 프로젝트에서 쓰이는 경우만 생각해서 제한적으로 구현하였고 `isFull`의 값에 따라서 컴포넌트 구성에 차이가 있습니다.   
`isFull`이 true인 경우, 
- `headerContent`에 값을 넣어서 헤더에 제목을 넣어야 합니다. 
- `footerButtonText`에 값을 넣어서 버튼에 문자열을 넣어야 합니다.
`isFull`이 false인 경우는 특별한 사항은 없습니다.
`isOpen`과 `onClose`는 Chakra의 Hook인 useDisclosure를 부모 컴포넌트에서 선언 후 CommonDrawer 컴포넌트에 넣어줘야 합니다.
`onClickFooterButton`는 푸터에 있는 버튼에 이벤트를 전달하면 됩니다.
아래의 코드는 예시입니다.
```typescript
// isFull이 true인 경우
const { isOpen, onOpen, onClose } = useDisclosure();
return (
<>
<Button
color="white"
bgColor="blue.300"
height="40px"
width="290px"
_hover={{ bgColor: "blue.300" }}
onClick={onOpen}
>
아이템
</Button>
<CommonDrawer
isOpen={isOpen}
onClose={onClose}
onClickFooterButton={() => {}}
isFull={true}
headerContent={
<Text
color="blue.900"
fontSize="2xl" …
```
> [OMCT-77] CommonDrawer 컴포넌트 구현

- src/components/common/Image/index.tsx
> [OMCT-110] CommonImage 컴포넌트 구현

- src/components/common/Avatar/index.tsx
size,src 변화에 따라서 변경되는  CommonAvatar 컴포넌트 구현
isOwner 경우에는 마이페이지 하나만 적용이 되서 크기는 고정 시켜놨습니다!
> [OMCT-100] CommonAvatar 컴포넌트 구현

- src/components/common/Header/index.tsx
Header 컴포넌트를 구현했습니다.
Router 설정이 아직 안되어있어서 그런지 npm run dev를 했을때 오류가 생깁니다.
Text컴포넌트는 추후 정호님이 만들어주시는 텍스트 컴포넌트로 변경하겠습니다!
> [OMCT-111] Header 컴포넌트 구현

- src/components/common/Select/index.tsx
CommonSelect 컴포넌트를 구현했습니다.
option의 value로 `latest`, `popularity`가 있습니다.
컴포넌트 props의 타입은 아래와 같습니다.
```typescript
interface CommonSelectProps {
width?: `${number}rem`;
height?: `${number}rem`;
fontSize?: `${number}rem`;
onChange: ChangeEventHandler<HTMLSelectElement>;
}
```
사용방법은 아래와 같습니다.
```javascript
<CommonSelect onChange={(e) => console.log(e.target.value)} />
```
> [OMCT-122] CommonSelect 컴포넌트 구현

- src/components/common/Profile/index.tsx
Profile 컴포넌트를 구현했습니다!
api 나오고 나서 한번 더 수정하도록하겠습니다! 🥲
src는 없을경우 기본이미지를 보여주는게 맞는것같아 타입 선택으로 두었습니다!
> [OMCT-105] Profile 컴포넌트 구현

- src/components/common/Footer/index.tsx
Footer 컴포넌트를 구현했습니다!
아이콘은 디자인보고 추후에 수정될수도있습니다!
> [OMCT-119] Footer 컴포넌트 구현

- src/components/common/Input/index.tsx
CommonInput 컴포넌트 구현했습니다!
**사용예시**
비밀번호 구현할때 눈모양
```
<CommonInput
size="md"
label="비밀번호"
type={showPassword ? 'text' : 'password'}
placeholder="비밀번호를 입력해주세요"
error={errors.password}
rightIcon={
<Box onClick={() => setShowPassword.toggle()}>
<CommonIcon type={showPassword ? 'eye' : 'eyeSlash'} size="1.25rem" />
</Box>
}
{...register('password', {
required: 'This is required',
minLength: { value: 4, message: 'Minimum length should be 4' },
})}
/>
```
검색 구현할때 검색어 삭제버튼
```
<CommonInput
size="lg"
label="검색"
type="text"
placeholder="검색어를 입력해주세요"
error={errors.search}
leftIcon={<CommonIcon type="search" size="1.25rem" />}
rightIcon={
<Box onClick={() => resetField('search')}>
<CommonIcon type="circleXmark" size="1.25rem" />
</Box>
}
{...register('search', {
required: 'This is required', …
```
> [OMCT-108] CommonInput 컴포넌트 구현

- src/App.tsx
- src/main.tsx
- src/routes/index.ts
- src/routes/router.tsx
router를 구현했습니다.
path는 [노션](https://www.notion.so/prgrms/6b3a2485da5840e387e41bd402108227?pvs=4)에 작성한 내용을 바탕으로 작성했고
현재 element에는 임시로 path를 작성해놨습니다.
추후에 페이지가 완성될때마다 추가하면 될 것 같습니다.
> [OMCT-125] router 구현

- src/shared/components/Avatar/index.tsx
CommonAvatar 컴포넌트를 수정했습니다.
CommonAvatar의 props 타입명이 컴포넌트명과 동일하여 타입이 export 되는 부분을 수정했습니다.
onClick prop을 바로 사용하게끔 수정했습니다.
> [OMCT-153] CommonAvatar 컴포넌트 수정

- src/core/routes/router.tsx
- src/shared/components/Avatar/index.tsx
- src/shared/components/Button/index.tsx
- src/shared/components/Card/index.tsx
- src/shared/components/Footer/index.tsx
- src/shared/components/Header/index.tsx
- src/shared/components/IconButton/index.tsx
- src/shared/components/Menu/index.tsx
- src/shared/components/Profile/index.tsx
- src/shared/components/Radio/RadioCard.tsx
- src/shared/components/Tag/index.tsx
- src/shared/components/Text/index.tsx
- src/shared/components/Toast/index.tsx
- src/shared/components/index.ts
- src/shared/hooks/useCustomToast.tsx
- tsconfig.json
경로 별칭을 추가했습니다.
코드 컨벤션에서 정한 내용을 바탕으로 src경로를 @로 지정했습니다.
기존에 별칭이 사용되지 않던 파일들의 내용을 전부 수정했습니다.
> [OMCT-143] 경로 별칭 추가 및 반영

- public/mockServiceWorker.js
- src/core/mocks/browser.ts
- src/core/mocks/handler/vote.ts
- src/core/mocks/response/vote.ts
msw 투표 핸들러 작성 완료했습니다!
- 에러 처리할수 있는거는 최대한 작성했습니다!
- 반환타입에러는 잡을려고 노력했으나 실력이 부족해서 못잡았습니다ㅠㅠ
- 투표 전체 조회는 hobby와 statusCondition를 필수로 작성해야지 오류가 안나오고 잘 작동됩니다!
```
import { Button } from '@chakra-ui/react';
import axios from 'axios';
const BASEURL = `/api/votes`;
const App = () => {
const createVote = () => {
axios
.post(`${BASEURL}`, {
hobby: '농구',
content: '어떤 농구화가 더 이쁜가?',
option1ItemId: 1,
option2ItemId: 2,
})
.then((res) => console.log(res));
};
const joinVote = () => {
axios
.post(`${BASEURL}/1/participation`, {
itemId: 1,
})
.then((res) => console.log(res));
};
const detailVote = () => {
axios.get(`${BASEURL}/1`).then((res) => console.log(res));
};
const deleteVote = () => {
axios.delete(`${BASEURL}/1`).then((res) => console.log(res));
};
const searchVote = () => { …
```
> [OMCT-79] Vote handler 작성 및 서비스워커 등록

- src/shared/components/Divider/index.tsx
CommonDivider 컴포넌트를 수정했습니다.
변수 `sizes`가 상수로 사용되고 있기때문에 코드 컨벤션에 맞게 `SIZES`로 수정했습니다.
> [OMCT-155] CommonDivider 컴포넌트 수정

- src/shared/components/DateText/index.tsx
> [OMCT-149] DateText 컴포넌트 구현

- src/core/mocks/browser.ts
- src/core/mocks/handler/feed.ts
- src/core/mocks/response/feed.ts
Feed Handler 작성했습니다
- 아직 댓글은 백엔드쪽에서 미완성이여서 나와있는대로 다 작성해보았습니다!
- 꼭 넣어야하는건 다 넣어야지 오류가 안나오고 동작이 됩니다!
- 
```
import { Button } from '@chakra-ui/react';
import axios from 'axios';
const BASEURL = `/api/feeds`;
const App = () => {
const createFeed = () => {
axios
.post(`${BASEURL}`, { hobby: 'baseball', bucketId: 1, content: '이거 좋다' })
.then((res) => console.log(res));
};
const deleteFeed = () => {
axios.delete(`${BASEURL}/1`).then((res) => console.log(res));
};
const editFeed = () => {
axios.put(`${BASEURL}/1`, { content: '이거는 수정' }).then((res) => console.log(res));
};
const createComment = () => {
axios.post(`${BASEURL}/1/comments`, { comment: '이거는 댓글' }).then((res) => console.log(res));
};
const adoptionComment = () => {
axios.post(`${BASEURL}/1/comments/1/adoption`).then((res) => …
```
> [OMCT-81] Feed handler 작성

- .eslintrc.cjs
- package-lock.json
- package.json
import 순서 설정을 했습니다!
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md
https://tesseractjh.tistory.com/305
위의 링크를 참고하면 좋을것같습니당!
> [OMCT-144] import/order 설정

- src/shared/components/Text/index.tsx
- children 타입 수정
-` color='inherit',onOfLine=1 `기본값 할당
> [OMCT-159] CommonText 컴포넌트 수정

- src/App.tsx
App의 레이아웃을 설정했습니다.
대부분의 페이지가 header, body, footer 형식으로 분리가 되어질텐데 
아래의 예시를 참고하시고 스타일 작성에 도움이 되면 좋겠습니다.
```javascript
<AppContainer>
<Header>헤더</Header>
<Body>내용</Body>
<Footer>푸터</Footer>
</AppContainer>
(...)
const Header = styled.div`
height: 100px;
width: 100%;
`;
const Body = styled.div`
overflow-y: scroll;
height: 100%;
width: 100%;
`;
const Footer = styled.div`
height: 100px;
width: 100%;
`;
```
> [OMCT-164] App 레이아웃 설정

- src/core/mocks/browser.ts
- src/core/mocks/handler/item.ts
- src/core/mocks/response/item.ts
> [OMCT-78] MSW Item handler 작성

- src/shared/components/Badge/index.tsx
CommonBadge 컴포넌트를 수정했습니다.
기존에 아이콘을 직접 가져와서 사용했던 부분을 CommonIcon으로 대체하고
Box에 flex를 줬던 부분을 Flex로 대체했습니다.
width는 fit-content로 수정하고 gap의 단위를 rem으로 수정했습니다.
> [OMCT-154] CommonBadge 컴포넌트 수정

- src/shared/components/Header/index.tsx
- src/shared/components/Image/index.tsx
Header 컴포넌트를 flex에서 box로 변경했습니다.
Image 타입을 수정했습니다!
> [OMCT-174] Header 컴포넌트 수정, Image 타입 수정

- src/features/feed/components/FeedItem/index.tsx
- src/features/feed/components/FeedItem/style.tsx
FeedItem 컴포넌트를 구현했습니다.
UI 우선으로 구현하였고 api가 나오면 기능까지 구현하겠습니다.
> [OMCT-162] FeedItem 컴포넌트 구현

- src/shared/components/Button/index.tsx
- src/shared/components/Radio/RadioCard.tsx
- src/shared/components/Radio/index.tsx
버튼에 variant 기본값이 soild라 뺀것도 있습니다!
라디오 스타일을 조금 수정했습니다.
> [OMCT-185] Common Radio, Button 컴포넌트 수정

- src/core/routes/router.tsx
- src/features/vote/components/VoteSelectItem/index.tsx
- src/features/vote/components/VoteSelectItem/style.ts
- src/pages/Vote/VoteCreate/index.tsx
- src/pages/Vote/VoteCreate/style.ts
투표 생성페이지 ui를 구현했습니다.
보여지는것에만 집중했고 api연동하면서 계속해서 리팩토링할 예정입니다!
> [OMCT-181] 투표 생성페이지 ui 구현

- src/core/routes/router.tsx
- src/pages/Item/Create/index.tsx
- src/pages/Item/Create/style.tsx
- src/shared/components/Input/index.tsx
주목할 점
-  react-hook-form을 이용해서 유효성 검사를 이용해서 스크립트 태그 방지했습니다
-  정규표현식을 이용해서` https://www`.으로 시작해야지 작동이 되도록했습니다
-  `mode:onChange`를 활용해서 실시간으로 유효성 검사가 감지되도록 했습니다
-  button disabled는 취미와 이상한 url이면 안되도록 막아놨습니다
> [OMCT-169] Item 생성 페이지 ui 구현 / CommonInput type 수정

- .env.example
- .gitignore
- src/core/service/axios.ts
- src/shared/utils/index.ts
- src/shared/utils/storage.ts
- .env.example 파일 추가
- axios 파일에 주석 처럼 예상 동작을 작성해보았습니다!
- localStorage 유틸함수를 작성해보았습니다!
> [OMCT-201] 기본 Axios 세팅

- src/core/service/axios.ts
- src/shared/utils/storage.ts
token이 없을때 발생하는 상황에 대처하는 axios 설정/LocalStorage 수정
> [NO-JIRA] token이 없을때 발생하는 상황에 대처하는 axios 설정/LocalStorage 수정

- src/core/routes/router.tsx
- src/pages/Item/Review/index.tsx
- src/pages/Item/Review/style.tsx
- src/shared/components/Slider/index.tsx
ItemReview 페이지 구현했습니다!
- 추가할 점
- 버튼 disabled 되는 상황 정의
- 로딩 중일때 스켈레톤 적용
- re-rendering 줄이기
- 로그인 되었을때 이용하기!
> [OMCT-171] ItemReview 페이지 ui 구현/Slider 컴포넌트 속성 추가

- src/core/service/axios.ts
- src/features/item/service/handler.ts
- src/features/item/service/index.ts
- src/features/item/service/types.ts
- src/shared/types/item.ts
- src/shared/utils/storage.ts
Item Handler 작성했습니다
Storage 수정했습니다!
- setItem 시 `JSON.stringify(value)` 로 되도록 했습니다.
- getItem 시 `JSON.parse(value)` 로 되도록 했습니다.
> [OMCT-223] Item Axios handler 작성/ storage 수정

- src/features/feed/service/handler.ts
- src/features/feed/service/index.ts
- src/features/feed/service/types.ts
- src/features/hobby/handler.ts
- src/features/hobby/index.ts
- src/features/hobby/types.ts
- src/pages/Feed/FeedDetail/index.tsx
- src/pages/Feed/FeedHome/index.tsx
- src/shared/service/handler.ts
- src/shared/types/feed.ts
- src/shared/types/hobby.ts
피드 api를 부분적으로 구현하였고 타입을 정리하기위해 빠른 PR을 날립니다.
> [OMCT-225] 피드 api 부분적 구현

- .husky/pre-push
> [NO-JIRA] husky pre-push 설정 추가

- src/features/item/components/ItemComment/index.tsx
- src/features/item/service/handler.ts
- src/features/item/service/index.ts
- src/features/item/service/types.ts
- src/pages/Item/Detail/index.tsx
- src/pages/Item/List/index.tsx
- src/shared/types/feed.ts
- src/shared/types/index.ts
- src/shared/types/item.ts
- src/shared/types/member.ts
- src/shared/types/review.ts
> [OMCT-235] Axios handler 구현

- src/features/review/service/handler.ts
- src/features/review/service/index.ts
- src/features/review/service/types.ts
> [OMCT-242] review handler 작성

- src/pages/Bucket/BucketCreate/index.tsx
- src/pages/Feed/FeedCreate/index.tsx
- src/pages/Feed/FeedDetail/index.tsx
- src/pages/Vote/VoteCreate/index.tsx
- src/shared/hooks/index.ts
- src/shared/hooks/useDrawer.tsx
useDrawer hook을 구현했습니다.
기존에 사용하던 chakra의 useDisclosure hook을 바로 사용하고 있었어서 
이를 useDrawer로 한번 감싸줬습니다.
> [NO-JIRA] useDrawer hook 구현

- src/pages/Member/MemberEdit/index.tsx
- src/pages/Member/MemberEdit/style.tsx
- src/shared/components/Textarea/index.tsx
> [OMCT-251] MemberEdit 페이지 UI 구현

- src/features/bucket/service/handler.ts
- src/features/bucket/service/index.ts
- src/features/bucket/service/queryOption.ts
- src/features/bucket/service/types.ts
- src/shared/types/bucket.ts
- src/shared/types/index.ts
버킷 관련 api handler를 구현했습니다.
추가적으로 queryOption도 구현했습니다.
> [OMCT-260] 버킷 api handler 구현

- src/core/routes/router.tsx
- src/features/comment/hooks/useComments.ts
- src/features/comment/service/index.ts
- src/features/comment/service/queryOption.ts
- src/features/comment/service/types.ts
- src/features/feed/components/FeedComment/index.tsx
- src/features/feed/components/FeedItem/index.tsx
- src/features/item/components/ItemComment/index.tsx
- src/pages/Feed/FeedDetail/index.tsx
- src/pages/Feed/FeedDetail/style.tsx
- src/pages/Feed/FeedHome/index.tsx
- src/pages/Home/index.tsx
- src/shared/components/Profile/index.tsx
댓글 api를 연결했습니다.
현재 데이터가 없어서 확인을 못하는게 아쉽습니다...
Profile 컴포넌트의 prop으로 id를 받아올 필요가 없어서 삭제했습니다.
> [OMCT-267] 댓글 api 연결

- index.html
> [NO-JIRA] meta태그 추가

- index.html
> [NO-JIRA] meta 태그 삭제

- src/features/member/service/handler.ts
- src/features/member/service/types.ts
JWT 유효성 검사 api handler를 구현했습니다.
실수로 dev에 머지해버렸네요... 죄송합니다. 😭
> [OMCT-282] JWT 유효성 검사 api handler 구현

- src/pages/Member/Signup/index.tsx
1. 오타를 수정했습니다.
2. 닉네임 및 이메일 중복확인을 한뒤, 
기존 : 중복확인한 닉네임과 이메일이 아닌 다른 값을 입력해도 회원가입 폼 제출이 가능했음
수정 후 :  회원가입 폼제출을 했을때 중복확인한 값과 같지 않다면 api 요청을 못보내도록 수정
> [OMCT-258] 회원가입페이지 오타 수정, 예외 처리 강화

- src/features/item/service/handler.ts
- src/features/item/service/queryOption.ts
- src/features/item/service/types.ts
- src/shared/types/item.ts
> [OMCT-296] 나의 아이템 목록 조회 api handler 작성

- src/features/vote/components/VoteInProgress/index.tsx
- src/features/vote/components/VoteInProgress/style.tsx
- src/features/vote/components/Votes/index.tsx
- src/features/vote/hooks/index.ts
- src/features/vote/hooks/useCancelVote.ts
- src/pages/Vote/VoteCreate/index.tsx
- src/pages/Vote/VoteDetail/index.tsx
진행중인 투표 페이지와 투표참여 api를 구현하였습니다.
https://github.com/bucket-back/bucket-back-frontend/assets/104294861/f69532b2-58f5-4d12-a510-33d517b63cc5
> [OMCT-180] 진행중인투표 페이지, 투표 참여 api 구현

- src/features/bucket/service/queryOption.ts
- src/features/bucket/service/types.ts
- src/features/comment/components/CommentItem/index.tsx
- src/features/feed/components/FeedSelectBucket/index.tsx
- src/features/feed/hooks/index.ts
- src/features/feed/hooks/useCreateFeed.ts
- src/pages/Feed/FeedCreate/index.tsx
- src/pages/Feed/FeedCreate/style.tsx
- src/pages/Feed/FeedDetail/index.tsx
피드 생성 기능을 구현했습니다.
버킷을 고르고 나서 생성 페이지로 돌아오면 선택된 버킷이 표시되지 않아서 이부분을 수정해야합니다...
> [OMCT-295] 피드 생성 기능 구현

- src/core/routes/router.tsx
- src/pages/Inventory/InventoryCreate/index.tsx
- src/pages/Inventory/InventoryDetail/index.tsx
- src/pages/Inventory/InventoryHome/index.tsx
- src/pages/Inventory/InventoryHome/style.ts
- src/pages/index.ts
> [OMCT-301] 인벤토리 목록 ui 구현 

- src/features/bucket/components/BucketSelectItem/index.tsx
- src/features/bucket/components/BucketSelectItem/style.ts
- src/features/bucket/components/index.ts
- src/features/bucket/hooks/index.ts
- src/features/bucket/hooks/useCreateBucket.ts
- src/features/bucket/service/handler.ts
- src/features/bucket/service/types.ts
- src/pages/Bucket/BucketCreate/index.tsx
- src/pages/Bucket/BucketCreate/style.ts
- src/shared/types/bucket.ts
버킷 생성 기능을 추가했습니다.
선택시 스타일이 좋지않아 추후에 수정해야할 것 같습니다.
> [OMCT-293] 버킷 생성 기능 추가

- src/features/item/components/index.ts
- src/features/item/hooks/useTakeItem.ts
- src/pages/Item/Detail/index.tsx
- src/pages/Item/Detail/style.tsx
아이템 담기 시 동작 수정/아이템 디테일 페이지 수정했습니다!
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/b51f804a-6eae-4249-8b14-37b82ad62432
> [NO JIRA] 아이템 담기 시 동작 수정/아이템 디테일 페이지 수정

- src/features/inventroy/components/InventorySelectItem/index.tsx
- src/features/inventroy/components/InventorySelectItem/style.ts
- src/pages/Inventory/InventoryCreate/index.tsx
- src/pages/Inventory/InventoryCreate/style.ts
- src/pages/Inventory/InventoryDetail/index.tsx
- src/pages/Inventory/InventoryDetail/style.ts
> [OMCT-302]인벤토리 상세페이지, 인벤토리 생성페이지 ui 구현

- src/core/routes/router.tsx
- src/features/item/components/ItemComment/index.tsx
- src/features/review/hooks/index.ts
- src/features/review/hooks/useEditReview.ts
- src/features/review/hooks/usePostReview.ts
- src/features/review/service/handler.ts
- src/features/review/service/queryOption.ts
- src/features/review/service/types.ts
- src/pages/Item/Detail/index.tsx
- src/pages/Item/ReviewEdit/index.tsx
- src/pages/Item/ReviewEdit/style.tsx
- src/pages/index.ts
- src/shared/components/Slider/index.tsx
아이템 리뷰 수정 api 연결 완료했습니다!
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/ae69e728-15c8-4961-9900-10701f381cab
> [OMCT-291] 리뷰 수정 api 연결

- src/features/inventroy/service/handler.ts
- src/features/inventroy/service/types.ts
- src/shared/types/inventory.ts
> [OMCT-305] 인벤토리 handler api 구현

- src/features/item/components/ItemComment/index.tsx
- src/features/item/hooks/usePostItem.ts
- src/features/review/hooks/index.ts
- src/features/review/hooks/useDeleteReview.ts
- src/features/review/hooks/useEditReview.ts
- src/pages/Item/Detail/index.tsx
리뷰 삭제 api 연결
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/e0350a9f-7a58-47cf-93c0-bad82ee0b3a8
> [OMCT-396] 리뷰 삭제 api 연결

- src/features/item/components/ItemList/index.tsx
- src/pages/Item/Detail/index.tsx
- src/pages/Item/List/index.tsx
아이템 리스트 api 연결했습니다
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/a5aa39a1-ec1b-4b92-81a4-23e434c501d6
> [OMCT-308] 아이템 리스트 api 연결

- src/features/feed/components/FeedItem/index.tsx
- src/features/feed/hooks/index.ts
- src/features/feed/hooks/useDeleteFeed.ts
- src/pages/Bucket/BucketCreate/index.tsx
- src/pages/Feed/FeedDetail/index.tsx
피드를 삭제하는 기능을 추가했습니다.
추가로 버킷 페이지에서 새로고침시 발생하는 오류를 수정했습니다.
> [OMCT-314] 피드 삭제 기능 추가

- src/features/item/service/handler.ts
- src/features/item/service/queryOption.ts
- src/features/item/service/types.ts
- src/features/search/service/handler.ts
- src/features/search/service/index.ts
- src/features/search/service/queryOption.ts
- src/features/search/service/types.ts
> [OMCT-323] 검색 api handler 작성

- src/features/member/components/MemberPasswordForm/index.tsx
- src/features/member/components/MemberPasswordForm/style.ts
- src/features/member/components/index.ts
- src/features/member/hooks/index.ts
- src/features/member/hooks/useUpdatePassword.ts
- src/features/member/service/queryOption.ts
- src/pages/Member/MemberPassword/index.tsx
- src/pages/Member/MemberPassword/style.tsx
비밀번호 변경 기능을 연결했습니다.
그리고 컴포넌트를 분리했으며 
추후에 토큰 유효성 검사를 할 것 같아서 queryOption에 token을 추가했습니다.
> [OMCT-326] 비밀번호 변경 기능 연결

- src/features/feed/hooks/index.ts
- src/features/feed/hooks/useUpdateFeed.ts
- src/features/feed/service/handler.ts
- src/pages/Feed/FeedUpdate/index.tsx
피드 수정 api를 연결해서 수정 기능을 구현했습니다.
특별한 사항은 없으며 조금 다른점은 이전 피드 내용의 값을 넣기위해 defaultValues가 아닌 values를 사용하여 구현했습니다.
> [OMCT-337] 피드 수정 api 연결

- src/core/routes/router.tsx
- src/features/bucket/components/BucketUpdateItem/index.tsx
- src/features/bucket/components/BucketUpdateItem/style.ts
- src/features/bucket/components/index.ts
- src/features/bucket/hooks/index.ts
- src/features/bucket/hooks/useDeleteBucket.ts
- src/features/bucket/hooks/useUpdateBucket.ts
- src/features/bucket/service/handler.ts
- src/features/bucket/service/queryOption.ts
- src/features/bucket/service/types.ts
- src/pages/Bucket/BucketDetail/index.tsx
- src/pages/Bucket/BucketDetail/style.ts
- src/pages/Bucket/BucketHome/index.tsx
- src/pages/Bucket/BucketHome/style.ts
- src/pages/Bucket/BucketUpdate/index.tsx
- src/pages/Bucket/BucketUpdate/style.ts
- src/pages/Feed/FeedUpdate/index.tsx
- src/pages/index.ts
- src/shared/components/Header/index.tsx
- src/shared/types/bucket.ts
버킷 관련 api를 연결했습니다.
버킷 수정 페이지는 제대로 동작하지않지만 커밋수가 많아져서 일단 pr을 올려봅니다.
pr을 나눠서 올렸어야했는데... 죄송합니다.
> [OMCT-343] 버킷 관련 api 연결 및 수정 페이지 임시로 추가

- src/features/search/components/index.ts
- src/features/search/components/latelySearch/index.tsx
- src/features/search/components/latelySearch/style.tsx
- src/features/search/components/searchForm/index.tsx
- src/features/search/components/searchList/index.tsx
- src/features/search/components/searchList/style.tsx
- src/features/search/service/handler.ts
- src/features/search/service/index.ts
- src/features/search/service/queryOption.ts
- src/features/search/service/types.ts
- src/pages/Search/SearchHome/index.tsx
- src/pages/Search/SearchMain/index.tsx
- src/pages/Search/SearchMain/style.tsx
검색 api 연결 했습니다
컴포넌트도 분리를 할려고 노력했습니다ㅠㅠ
나중에 코드 리펙토링을 진행하겠습니다!
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/86278d4c-7f50-4b70-8e61-1e8b5f1c3c11
**아직 디바운스는 적용을 못했습니다! 검색결과 페이지 완성하고 도전해보겠습니다!**
> [OMCT-321] 검색 api 연결

- src/features/bucket/components/BucketSelectedItems/index.tsx
- src/features/bucket/components/BucketSelectedItems/style.ts
- src/features/bucket/components/index.ts
- src/features/bucket/hooks/useCreateBucket.ts
- src/features/bucket/hooks/useUpdateBucket.ts
- src/pages/Bucket/BucketCreate/index.tsx
- src/pages/Bucket/BucketUpdate/index.tsx
- src/shared/components/Radio/RadioCard.tsx
제대로 동작하지않던 버킷 수정 기능을 구현했습니다.
추가로 버킷 생성시 아이템 하나 이상이면 생성 가능하도록 수정했습니다.
> [OMCT-354] 버킷 수정 기능 구현

- src/features/hobby/components/HobbySelector/index.tsx
- src/features/hobby/components/HobbySelector/style.ts
- src/features/inventory/components/ UpdateInventoryDetail/index.tsx
- src/features/inventory/components/DeleteInventoryDetail/index.tsx
- src/features/inventory/components/InventorySelectItem/index.tsx
- src/features/inventory/service/types.ts
- src/pages/Inventory/InventoryCreate/index.tsx
- src/pages/Inventory/InventoryDetail/index.tsx
- src/pages/Inventory/InventoryHome/index.tsx
인벤토리 페이지 리팩토링을 하였습니다.
1. 수정 인벤토리와 삭제 인벤토리 컴포넌트를 만들어 분리하였습니다.
2. useQuery를 분리하였습니다. 
3. HobbySelector컴포넌트를 만들었습니다.
> [OMCT-297] 인벤토리 페이지 리팩토링

- src/core/routes/router.tsx
- src/features/search/components/index.ts
- src/features/search/components/searchItemList/index.tsx
- src/features/search/components/searchItemList/style.tsx
- src/features/search/components/searchVoteList/index.tsx
- src/features/search/components/searchVoteList/style.tsx
- src/pages/Search/SearchHome/style.tsx
- src/pages/Search/SearchResult/index.tsx
- src/pages/Search/SearchResult/style.tsx
- src/pages/index.ts
- src/shared/components/Tabs/index.tsx
검색 결과 페이지 ui 구현했습니다!
아이템 검색 결과 페이지
투표 검색 결과 페이지
> [OMCT-342] 검색 결과 페이지 ui 구현

- src/features/item/hooks/index.ts
- src/features/item/hooks/useDeleteItem.ts
- src/features/item/service/handler.ts
- src/features/item/service/types.ts
- src/pages/Item/List/index.tsx
아이템 삭제 api 연결했습니다!
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/dd8beeb8-7bbe-4888-bf75-19020393ae58
> [OMCT-309] 아이템 삭제 api 연결

- src/features/item/components/ItemComment/index.tsx
- src/pages/Item/Detail/index.tsx
리뷰 ui 수정했습니다!
- 본인이 작성한것만 수정,삭제가 가능한 ui 표시
- 인벤토리 빼고 나머지 내용 삭제
> [OMCT-374] 리뷰 ui 수정

- src/features/search/components/searchForm/index.tsx
- src/features/search/hooks/index.ts
- src/features/search/hooks/useDebounce.ts
검색페이지에 디바운스 적용했습니다!
0.3초마다 적용되게 했습니다!
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/b8054d6c-e743-4d07-b469-94e2932a8800
> [OMCT-370] 검색 디바운스 적용

- src/features/feed/components/FeedItemsDetail/index.tsx
- src/features/search/components/latelySearch/index.tsx
- src/features/search/components/searchForm/index.tsx
- src/features/search/components/searchItemList/style.tsx
- src/features/search/components/searchList/index.tsx
- src/features/search/components/searchVoteList/style.tsx
- src/features/search/service/index.ts
- src/features/search/service/searchLocalStorage.ts
- src/shared/utils/ellipsisName.ts
검색 QA 피드백 구현했습니다!
- 최대 10개까지 저장 가능(나중에 검색한거 삭제)
- 단어만 입력시 결과 페이지로 이동
- gap을 통해서 추가하러가기 문구 간격 넓히기
> [OMCT-382] 검색 QA 피드백 구현

- src/features/hobby/components/HobbySelector/index.tsx
- src/features/inventory/components/InventorySelectItem/index.tsx
- src/features/vote/components/VoteInProgress/index.tsx
- src/features/vote/components/VoteItem/index.tsx
- src/features/vote/components/VoteItem/style.tsx
- src/features/vote/components/VoteOptionItem/index.tsx
- src/pages/Inventory/InventoryCreate/index.tsx
- src/pages/Inventory/InventoryDetail/index.tsx
- src/pages/Inventory/InventoryHome/index.tsx
- src/pages/Member/Login/index.tsx
- src/pages/Vote/VoteCreate/index.tsx
- src/pages/Vote/VoteDetail/index.tsx
1. 투표 상세페이지 컴포넌트를 분리하였습니다 + 투표 상세페이지에 formatNumber를 추가하였습니다.
2. 투표 생성할때 취미를 선택해도 아이템이 그대로 남도록 수정하였습니다.
3. 인벤토리 생성할때 취미를 선택해도 아이템이 그대로 남도록 수정하였습니다.
4. 로그인시 비밀번호 유효성 검사하던거를 제거하였습니다.
5. 진행중인 투표 무한스크롤 가져오는 size를 10에서 5로 줄였습니다.
> [OMCT-387] QA 1차 진행

- src/features/bucket/components/BucketList/style.ts
> [NO-JIRA] 나의 버킷 디자인 수정

- src/features/search/components/searchForm/index.tsx
- src/features/search/components/searchItemList/index.tsx
- src/features/search/components/searchList/index.tsx
- src/features/search/components/searchVoteList/index.tsx
- src/features/search/service/queryOption.ts
- src/pages/Search/SearchHome/style.tsx
- src/pages/Search/SearchResult/index.tsx
- src/pages/Search/SearchResult/style.tsx
검색 페이지 무한스크롤 구현했습니다
- 검색페이지에 scroll 수정했습니다!
- 리뷰에 맴버 id 할당했습니다!
- 중괄호 등 서버에 보낼때 인코딩 이슈가 있어서 수정했습니다!
https://github.com/bucket-back/bucket-back-frontend/assets/78207432/e7a53640-1773-469d-9563-9b53c2e662e2
> [OMCT-376] 검색 페이지 무한스크롤 구현

- src/App.tsx
- src/features/bucket/components/BucketSelectItem/index.tsx
- src/features/bucket/components/BucketSelectItem/style.ts
- src/features/comment/hooks/useAddComment.ts
- src/features/feed/components/FeedSelectBucket/style.tsx
- src/features/item/service/queryOption.ts
- src/pages/Bucket/BucketCreate/index.tsx
- src/pages/Bucket/BucketCreate/style.ts
- src/pages/Feed/FeedDetail/index.tsx
버킷 생성시 아이템 목록 무한 스크롤 구현했습니다.
추가적으로 아래의 작업을 했습니다.
- 댓글 작성후 레벨 오르면 멤버 상세 쿼리키 무효화
- 버킷 생성시 아이템을 많이 고르면 스타일이 이상해지는 현상 수정
- itemQueryOption의 myItems 수정
> [OMCT-393] 버킷 생성시 아이템 목록 무한 스크롤 구현

- src/features/rank/components/index.ts
- src/features/rank/components/rankList/index.tsx
- src/features/rank/components/rankList/style.tsx
- src/features/rank/service/handler.ts
- src/features/rank/service/index.ts
- src/features/rank/service/queryOption.ts
- src/features/rank/service/type.ts
- src/pages/Search/SearchMain/index.tsx
- src/pages/Search/SearchMain/style.tsx
랭킹 페이지 구현
- ui와 api 연결도 완료했습니다!
> [OMCT-396] 랭킹 페이지 구현

- index.html
- src/features/bucket/components/BucketSelectItem/index.tsx
- src/features/bucket/components/BucketSelectItem/style.ts
- src/features/comment/components/CommentItem/index.tsx
- src/features/feed/components/FeedHomeList/index.tsx
- src/features/feed/components/FeedItem/index.tsx
- src/features/feed/components/FeedItem/style.tsx
- src/features/feed/components/FeedMemberList/index.tsx
- src/features/feed/hooks/useDeleteFeed.ts
- src/features/feed/hooks/useUpdateFeed.ts
- src/features/member/components/MemberEditForm/index.tsx
- src/pages/Bucket/BucketDetail/index.tsx
- src/pages/Bucket/BucketDetail/style.ts
- src/pages/Feed/FeedCreate/index.tsx
- src/pages/Feed/FeedDetail/index.tsx
- src/pages/Feed/FeedUpdate/index.tsx
- src/pages/Member/MemberHome/index.tsx
- src/pages/Member/MemberHome/style.tsx
- src/shared/components/Footer/index.tsx
- src/shared/components/Icon/index.tsx
- src/shared/styles/ImageBorder.ts
QA 반영 및 개인적으로 찾은 오류를 수정했습니다.
QA 반영 부분
- 피드의 최대글자수는 200, 댓글의 최대글자수는 100으로 수정
개인적으로 찾은 오류 부분
- 피드 상세에서 피드 내용을 클릭시 버킷 아이템 모달이 나오는 부분
- 마이페이지에서 푸터 색상 변경 안되는 부분
- 멤버페이지에서 피드 삭제시 홈으로 가는 부분
- 피드 아이템이 6개 초과로 보이는 부분
그리고 아이템에 border 값을 줬습니다. (아이템 목록, 검색 목록, 아이템 상세, 인벤토리 아이템 목록 제외)
> [OMCT-394] QA 반영 및 개인적으로 찾은 오류 수정

- src/features/item/components/ItemComment/index.tsx
- src/features/review/hooks/useEditReview.ts
- src/features/review/hooks/usePostReview.ts
- src/features/review/service/queryOption.ts
- src/features/search/components/searchItemList/index.tsx
- src/features/search/service/types.ts
- src/pages/Item/Detail/index.tsx
- src/pages/Item/Detail/style.tsx
- src/pages/Item/List/style.tsx
- src/pages/Item/Review/index.tsx
- src/pages/Item/ReviewEdit/index.tsx
- src/shared/components/Header/index.tsx
QA 
- 아이템 리스트 padding 할당
- 아이템 상세 페이지 ui 수정
> [OMCT-391] 아이템 리뷰 무한 스크롤 / QA 반영

- src/features/vote/components/VoteSelectItem/index.tsx
> [OMCT-400] 투표페이지 전체 아이템 갯수 수정
